
include("utils_test.jl")
include("vega_general_test.jl")
include("vega_sankey_test.jl")
include("vega_sankey_regression_test.jl")
include("vega_sparse_matrix_test.jl")
include("vega_sparse_matrix_regression_test.jl")
include("sparse_matrix_helpers_test.jl")
include("svg_square_stack_table_test.jl")
include("svg_square_stack_table_regression_test.jl")